# Generated by Django 4.2.23 on 2025-08-05 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('gmail', models.EmailField(blank=True, max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('historial_deportivo', models.TextField(blank=True)),
                ('experiencias_gimnasios', models.TextField(blank=True)),
                ('historial_lesivo', models.TextField(blank=True)),
                ('enfermedades', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('frecuencia_semana', models.CharField(blank=True, max_length=50)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('pagado', models.BooleanField(default=True)),
                ('anulado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gymapp.member')),
            ],
            options={
                'unique_together': {('member', 'mes')},
            },
        ),
    ]
