# Generated by Django 4.2.23 on 2025-08-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estructura', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('fuerza_base', 'Fuerza base'), ('deportista', 'Deportista avanzado'), ('acondicionamiento', 'Acondicionamiento físico'), ('edad_temprana', 'Edad temprana'), ('original', 'Original')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='gymapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('series', models.CharField(blank=True, max_length=50)),
                ('repeticiones', models.CharField(blank=True, max_length=50)),
                ('peso', models.CharField(blank=True, max_length=50)),
                ('descanso', models.CharField(blank=True, max_length=50)),
                ('rir', models.CharField(blank=True, max_length=50)),
                ('sensaciones', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymapp.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gymapp.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('rutina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='gymapp.rutina')),
            ],
        ),
    ]
