# Generated by Django 4.2.23 on 2025-08-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_ejercicio_rutina_detallerutina_comentariorutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerutina',
            name='es_calentamiento',
            field=models.BooleanField(default=False),
        ),
    ]
