# Generated by Django 4.2.23 on 2025-08-27 14:55

import datetime
from django.db import migrations, models


def _mes_char_to_date(apps, schema_editor):
    Payment = apps.get_model('gymapp', 'Payment')
    for pago in Payment.objects.all():
        mes_text = pago.mes
        try:
            parsed = datetime.datetime.strptime(mes_text, "%m-%Y")
            pago.mes = parsed.replace(day=1).strftime("%Y-%m-%d")
            pago.save(update_fields=['mes'])
        except Exception:
            # Si ya está en formato correcto o es nulo, lo dejamos tal cual
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("gymapp", "0003_detallerutina_es_calentamiento"),
    ]

    operations = [
        migrations.RunPython(_mes_char_to_date, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="payment",
            name="mes",
            field=models.DateField(),
        ),
    ]
