# Generated by Django 4.2.23 on 2025-08-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gymapp", "0003_detallerutina_es_calentamiento"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("member", "mes"), name="unique_payment_mes"
            ),
        ),
    ]
