# Generated by Django 4.2.23 on 2025-08-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_alter_payment_mes'),
        ('gymapp', '0004_alter_payment_unique_together_and_more'),
    ]

    operations = [
    ]
