# Generated by Django 4.2.23 on 2025-09-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_merge_20250827_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(blank=True, choices=[('2', '2 días - $24.000'), ('3', '3 días - $27.000'), ('all', 'Todos - $30.000')], max_length=8, null=True),
        ),
    ]
